// Auto-generated by gen_grad12.py -- DO NOT EDIT BY HAND.
// 12-parameter Gauss-Newton specialization: per-residual gradients over
// [dwx,dwy,dwz,dtx,dty,dtz,df,dk1,dk2,dXx,dXy,dXz] at the perturbation
// origin. CSE over the 24 gradient entries + 2 residuals only.
#pragma once

__device__ __forceinline__ void BalResidualGrad12(
    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,
    Scalar R20,Scalar R21,Scalar R22,
    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,
    Scalar f_,Scalar k1_,Scalar k2_,Scalar ux,Scalar uy,
    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,
    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {
  Scalar x0 = R10*X0x + R11*X0y + R12*X0z;
  Scalar x1 = R20*X0x + R21*X0y + R22*X0z;
  Scalar x2 = t0z + x1;
  Scalar x3 = pow(x2, -2);
  Scalar x4 = R00*X0x + R01*X0y + R02*X0z;
  Scalar x5 = t0x + x4;
  Scalar x6 = pow(x5, 2);
  Scalar x7 = t0y + x0;
  Scalar x8 = pow(x7, 2);
  Scalar x9 = x6 + x8;
  Scalar x10 = x3*x9;
  Scalar x11 = pow(x9, 2);
  Scalar x12 = k1_*x10 + k2_*x11/pow(x2, 4) + 1;
  Scalar x13 = x0*x12;
  Scalar x14 = 1.0/x2;
  Scalar x15 = x0*x14;
  Scalar x16 = x1*x7 + x15*x6 + x15*x8;
  Scalar x17 = 2*x10;
  Scalar x18 = k1_ + k2_*x17;
  Scalar x19 = 2*x18;
  Scalar x20 = x14*x19;
  Scalar x21 = f_*x5;
  Scalar x22 = x21*x3;
  Scalar x23 = x1*x12;
  Scalar x24 = x12*x4;
  Scalar x25 = x14*x4;
  Scalar x26 = x1*x5 + x25*x6 + x25*x8;
  Scalar x27 = x19*x3;
  Scalar x28 = x27*x5;
  Scalar x29 = f_*x14;
  Scalar x30 = -x0*x5 + x4*x7;
  Scalar x31 = pow(x2, -3);
  Scalar x32 = -x19*x21*x31*x7;
  Scalar x33 = x12 + x17*x18;
  Scalar x34 = x12*x14;
  Scalar x35 = x34*x5;
  Scalar x36 = x31*x9;
  Scalar x37 = x11/pow(x2, 5);
  Scalar x38 = -R00*x5 - R10*x7 + R20*x14*x6 + R20*x14*x8;
  Scalar x39 = -R01*x5 - R11*x7 + R21*x14*x6 + R21*x14*x8;
  Scalar x40 = -R02*x5 - R12*x7 + R22*x14*x6 + R22*x14*x8;
  Scalar x41 = x27*x7;
  Scalar x42 = f_*x7;
  Scalar x43 = x3*x42;
  Scalar x44 = x34*x7;
  Scalar x45 = x12*x29;
  grad_res_x[0] = x22*(x13 + x16*x20);
  grad_res_x[1] = -x29*(x14*x24*x5 + x23 + x26*x28);
  grad_res_x[2] = x29*(x0*x12 - x28*x30);
  grad_res_x[3] = -x29*(x12 + x27*x6);
  grad_res_x[4] = x32;
  grad_res_x[5] = x22*x33;
  grad_res_x[6] = -x35;
  grad_res_x[7] = -x21*x36;
  grad_res_x[8] = -x21*x37;
  grad_res_x[9] = x29*(-R00*x12 + R20*x35 + x28*x38);
  grad_res_x[10] = x29*(-R01*x12 + R21*x35 + x28*x39);
  grad_res_x[11] = x29*(-R02*x12 + R22*x35 + x28*x40);
  grad_res_y[0] = x29*(x13*x14*x7 + x16*x41 + x23);
  grad_res_y[1] = -x43*(x20*x26 + x24);
  grad_res_y[2] = -x29*(x24 + x30*x41);
  grad_res_y[3] = x32;
  grad_res_y[4] = -x29*(x12 + x27*x8);
  grad_res_y[5] = x33*x43;
  grad_res_y[6] = -x44;
  grad_res_y[7] = -x36*x42;
  grad_res_y[8] = -x37*x42;
  grad_res_y[9] = x29*(-R10*x12 + R20*x44 + x38*x41);
  grad_res_y[10] = x29*(-R11*x12 + R21*x44 + x39*x41);
  grad_res_y[11] = x29*(-R12*x12 + R22*x44 + x40*x41);
  *res_x = -ux - x45*x5;
  *res_y = -uy - x45*x7;
}
