# Auto-generated by gen_grad12.py -- numpy twin of bal_grad12_generated.cuh
# (identical CSE temporaries, so FD validation exercises the shipped formula).
import numpy as np

def bal_residual_grad12(R00,R01,R02,R10,R11,R12,R20,R21,R22,
                        t0x,t0y,t0z,X0x,X0y,X0z,f_,k1_,k2_,ux,uy):
    x0 = R10*X0x + R11*X0y + R12*X0z
    x1 = R20*X0x + R21*X0y + R22*X0z
    x2 = t0z + x1
    x3 = x2**(-2)
    x4 = R00*X0x + R01*X0y + R02*X0z
    x5 = t0x + x4
    x6 = x5**2
    x7 = t0y + x0
    x8 = x7**2
    x9 = x6 + x8
    x10 = x3*x9
    x11 = x9**2
    x12 = k1_*x10 + k2_*x11/x2**4 + 1
    x13 = x0*x12
    x14 = 1/x2
    x15 = x0*x14
    x16 = x1*x7 + x15*x6 + x15*x8
    x17 = 2*x10
    x18 = k1_ + k2_*x17
    x19 = 2*x18
    x20 = x14*x19
    x21 = f_*x5
    x22 = x21*x3
    x23 = x1*x12
    x24 = x12*x4
    x25 = x14*x4
    x26 = x1*x5 + x25*x6 + x25*x8
    x27 = x19*x3
    x28 = x27*x5
    x29 = f_*x14
    x30 = -x0*x5 + x4*x7
    x31 = x2**(-3)
    x32 = -x19*x21*x31*x7
    x33 = x12 + x17*x18
    x34 = x12*x14
    x35 = x34*x5
    x36 = x31*x9
    x37 = x11/x2**5
    x38 = -R00*x5 - R10*x7 + R20*x14*x6 + R20*x14*x8
    x39 = -R01*x5 - R11*x7 + R21*x14*x6 + R21*x14*x8
    x40 = -R02*x5 - R12*x7 + R22*x14*x6 + R22*x14*x8
    x41 = x27*x7
    x42 = f_*x7
    x43 = x3*x42
    x44 = x34*x7
    x45 = x12*x29
    gx = [x22*(x13 + x16*x20),
          -x29*(x14*x24*x5 + x23 + x26*x28),
          x29*(x0*x12 - x28*x30),
          -x29*(x12 + x27*x6),
          x32,
          x22*x33,
          -x35,
          -x21*x36,
          -x21*x37,
          x29*(-R00*x12 + R20*x35 + x28*x38),
          x29*(-R01*x12 + R21*x35 + x28*x39),
          x29*(-R02*x12 + R22*x35 + x28*x40)]
    gy = [x29*(x13*x14*x7 + x16*x41 + x23),
          -x43*(x20*x26 + x24),
          -x29*(x24 + x30*x41),
          x32,
          -x29*(x12 + x27*x8),
          x33*x43,
          -x44,
          -x36*x42,
          -x37*x42,
          x29*(-R10*x12 + R20*x44 + x38*x41),
          x29*(-R11*x12 + R21*x44 + x39*x41),
          x29*(-R12*x12 + R22*x44 + x40*x41)]
    rx = -ux - x45*x5
    ry = -uy - x45*x7
    return np.array(gx), np.array(gy), rx, ry
