# Auto-generated by gen_grad17_fisheye.py -- numpy twin of
# fisheye_grad17_generated.cuh (identical CSE temporaries, so FD
# validation exercises the shipped formula).
import numpy as np
import math

def fisheye_residual_grad17(R00,R01,R02,R10,R11,R12,R20,R21,R22,
                            t0x,t0y,t0z,X0x,X0y,X0z,
                            fx_,fy_,cx_,cy_,k1_,k2_,k3_,k4_,ux,uy):
    x0 = R10*X0x + R11*X0y + R12*X0z
    x1 = R00*X0x + R01*X0y + R02*X0z
    x2 = t0x + x1
    x3 = x2**2
    x4 = R20*X0x + R21*X0y + R22*X0z
    x5 = t0z + x4
    x6 = x5**(-2)
    x7 = x3*x6
    x8 = t0y + x0
    x9 = x8**2
    x10 = x6*x9
    x11 = x10 + x7
    x12 = x11 + 1.0e-32
    x13 = math.sqrt(x12)
    x14 = 1/x13
    x15 = math.atan(x13)
    x16 = x15**2
    x17 = x15**4
    x18 = x15**6
    x19 = k1_*x16 + k2_*x17 + k3_*x18 + k4_*x15**8 + 1
    x20 = x15*x19
    x21 = x14*x20
    x22 = x0*x21
    x23 = 1/(x12*(x11 + 1.0))
    x24 = x19*x23
    x25 = 1/x5
    x26 = x0*x25
    x27 = x26*x3 + x26*x9 + x4*x8
    x28 = x25*x27
    x29 = x12**(-3/2)
    x30 = 2*x16
    x31 = x23*x30*(k1_ + k2_*x30 + 3*k3_*x17 + 4*k4_*x18)
    x32 = fx_*x2
    x33 = x32*x6
    x34 = x21*x4
    x35 = x1*x25
    x36 = x2*x21
    x37 = x2*x4 + x3*x35 + x35*x9
    x38 = x2*x6
    x39 = x37*x38
    x40 = x20*x29
    x41 = fx_*x25
    x42 = -x0*x2 + x1*x8
    x43 = x38*x42
    x44 = (x24 + x31 - x40)/x5**3
    x45 = x3 + x9
    x46 = x45*x6
    x47 = x15*x19*x29*x45*x6 - x21 - x24*x46 - x31*x46
    x48 = x21*x25
    x49 = x14*x15**3
    x50 = x2*x41
    x51 = x15**5
    x52 = x14*x50
    x53 = x15**7
    x54 = x15**9
    x55 = R20*x25
    x56 = R00*x2 + R10*x8 - x3*x55 - x55*x9
    x57 = x38*x56
    x58 = R21*x25
    x59 = R01*x2 + R11*x8 - x3*x58 - x58*x9
    x60 = x38*x59
    x61 = R22*x25
    x62 = R02*x2 + R12*x8 - x3*x61 - x61*x9
    x63 = x38*x62
    x64 = x21*x8
    x65 = x6*x8
    x66 = x27*x65
    x67 = fy_*x25
    x68 = x1*x21
    x69 = x25*x37
    x70 = fy_*x8
    x71 = x6*x70
    x72 = x42*x65
    x73 = x67*x8
    x74 = x14*x73
    x75 = x56*x65
    x76 = x59*x65
    x77 = x62*x65
    gx = [x33*(x15*x19*x25*x27*x29 - x22 - x24*x28 - x28*x31),
          x41*(x24*x39 + x31*x39 + x34 + x35*x36 - x39*x40),
          x41*(-x22 + x24*x43 + x31*x43 - x40*x43),
          x41*(x21 + x24*x7 + x31*x7 - x40*x7),
          x32*x44*x8,
          x33*x47,
          x2*x48,
          0,
          1,
          0,
          x49*x50,
          x51*x52,
          x52*x53,
          x52*x54,
          x41*(R00*x21 + x24*x57 + x31*x57 - x36*x55 - x40*x57),
          x41*(R01*x21 + x24*x60 + x31*x60 - x36*x58 - x40*x60),
          x41*(R02*x21 + x24*x63 + x31*x63 - x36*x61 - x40*x63)]
    gy = [x67*(x15*x19*x27*x29*x6*x8 - x24*x66 - x26*x64 - x31*x66 - x34),
          x71*(x24*x69 + x31*x69 - x40*x69 + x68),
          x67*(x24*x72 + x31*x72 - x40*x72 + x68),
          x2*x44*x70,
          x67*(x10*x24 + x10*x31 - x10*x40 + x21),
          x47*x71,
          0,
          x48*x8,
          0,
          1,
          x49*x73,
          x51*x74,
          x53*x74,
          x54*x74,
          x67*(R10*x21 + x24*x75 + x31*x75 - x40*x75 - x55*x64),
          x67*(R11*x21 + x24*x76 + x31*x76 - x40*x76 - x58*x64),
          x67*(R12*x21 + x24*x77 + x31*x77 - x40*x77 - x61*x64)]
    rx = cx_ - ux + x21*x50
    ry = cy_ - uy + x21*x73
    return np.array(gx), np.array(gy), rx, ry
