// Auto-generated by gen_grad17_fisheye_atan2.py -- DO NOT EDIT BY HAND.
// OPENCV_FISHEYE, COLMAP +z convention, free principal point,
// theta = atan2(rho, Pz): finite and smooth through the camera plane.
// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]
// at the perturbation origin. CSE over 34 gradient entries + 2 residuals.
#pragma once

__device__ __forceinline__ void FisheyeResidualGrad17A(
    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,
    Scalar R20,Scalar R21,Scalar R22,
    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,
    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,
    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,
    Scalar ux,Scalar uy,
    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,
    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {
  Scalar x0 = R20*X0x + R21*X0y + R22*X0z;
  Scalar x1 = R10*X0x + R11*X0y + R12*X0z;
  Scalar x2 = t0y + x1;
  Scalar x3 = R00*X0x + R01*X0y + R02*X0z;
  Scalar x4 = t0x + x3;
  Scalar x5 = (x4*x4);
  Scalar x6 = (x2*x2);
  Scalar x7 = x5 + x6 + 1.0000000000000001e-32;
  Scalar x8 = 1.0/x7;
  Scalar x9 = sqrt(x7);
  Scalar x10 = t0z + x0;
  Scalar x11 = atan2(x9, x10);
  Scalar x12 = (x11*x11);
  Scalar x13 = (x11*x11*x11*x11);
  Scalar x14 = pow(x11, 6);
  Scalar x15 = k1_*x12 + k2_*x13 + k3_*x14 + k4_*pow(x11, 8) + 1;
  Scalar x16 = 1.0/x9;
  Scalar x17 = x10*x16;
  Scalar x18 = x0*x17;
  Scalar x19 = x1*x9 + x18*x2;
  Scalar x20 = 1.0/((x10*x10) + x7);
  Scalar x21 = x15*x20;
  Scalar x22 = x19*x21;
  Scalar x23 = 2*x12;
  Scalar x24 = x23*(k1_ + k2_*x23 + 3*k3_*x13 + 4*k4_*x14);
  Scalar x25 = x20*x24;
  Scalar x26 = x19*x25;
  Scalar x27 = fx_*x16;
  Scalar x28 = x27*x4;
  Scalar x29 = x11*x15;
  Scalar x30 = x0*x29;
  Scalar x31 = x30*x8;
  Scalar x32 = x18*x4 + x3*x9;
  Scalar x33 = x21*x32;
  Scalar x34 = x25*x32;
  Scalar x35 = x16*x29;
  Scalar x36 = -x1*x4 + x2*x3;
  Scalar x37 = x29/pow(x7, 3.0/2.0);
  Scalar x38 = x36*x37;
  Scalar x39 = x10*x8;
  Scalar x40 = x21*x39;
  Scalar x41 = x36*x40;
  Scalar x42 = x25*x39;
  Scalar x43 = x36*x42;
  Scalar x44 = fx_*x4;
  Scalar x45 = x2*(-x37 + x40 + x42);
  Scalar x46 = x20*(x15 + x24);
  Scalar x47 = (x11*x11*x11);
  Scalar x48 = (x11*x11*x11*x11*x11);
  Scalar x49 = pow(x11, 7);
  Scalar x50 = pow(x11, 9);
  Scalar x51 = R00*x4 + R10*x2;
  Scalar x52 = x29*x8;
  Scalar x53 = x4*x52;
  Scalar x54 = R20*x9 - x17*x51;
  Scalar x55 = x21*x4;
  Scalar x56 = x25*x4;
  Scalar x57 = R01*x4 + R11*x2;
  Scalar x58 = R21*x9 - x17*x57;
  Scalar x59 = R02*x4 + R12*x2;
  Scalar x60 = R22*x9 - x17*x59;
  Scalar x61 = fy_*x16;
  Scalar x62 = x2*x61;
  Scalar x63 = fy_*x2;
  Scalar x64 = x2*x52;
  Scalar x65 = x2*x21;
  Scalar x66 = x2*x25;
  grad_res_x[0] = x28*(x0*x11*x15*x2*x8 - x22 - x26);
  grad_res_x[1] = x27*(x30 - x31*x5 + x33*x4 + x34*x4);
  grad_res_x[2] = fx_*(-x1*x35 - x38*x4 + x4*x41 + x4*x43);
  grad_res_x[3] = fx_*(x35 - x37*x5 + x40*x5 + x42*x5);
  grad_res_x[4] = x44*x45;
  grad_res_x[5] = -x44*x46;
  grad_res_x[6] = x35*x4;
  grad_res_x[7] = 0;
  grad_res_x[8] = 1;
  grad_res_x[9] = 0;
  grad_res_x[10] = x28*x47;
  grad_res_x[11] = x28*x48;
  grad_res_x[12] = x28*x49;
  grad_res_x[13] = x28*x50;
  grad_res_x[14] = x27*(R00*x11*x15 - x51*x53 - x54*x55 - x54*x56);
  grad_res_x[15] = x27*(R01*x11*x15 - x53*x57 - x55*x58 - x56*x58);
  grad_res_x[16] = x27*(R02*x11*x15 - x53*x59 - x55*x60 - x56*x60);
  grad_res_y[0] = x61*(x0*x11*x15*x6*x8 - x2*x22 - x2*x26 - x30);
  grad_res_y[1] = x62*(-x31*x4 + x33 + x34);
  grad_res_y[2] = fy_*(-x2*x38 + x2*x41 + x2*x43 + x3*x35);
  grad_res_y[3] = fy_*x4*x45;
  grad_res_y[4] = fy_*(x35 - x37*x6 + x40*x6 + x42*x6);
  grad_res_y[5] = -x46*x63;
  grad_res_y[6] = 0;
  grad_res_y[7] = x2*x35;
  grad_res_y[8] = 0;
  grad_res_y[9] = 1;
  grad_res_y[10] = x47*x62;
  grad_res_y[11] = x48*x62;
  grad_res_y[12] = x49*x62;
  grad_res_y[13] = x50*x62;
  grad_res_y[14] = x61*(R10*x11*x15 - x51*x64 - x54*x65 - x54*x66);
  grad_res_y[15] = x61*(R11*x11*x15 - x57*x64 - x58*x65 - x58*x66);
  grad_res_y[16] = x61*(R12*x11*x15 - x59*x64 - x60*x65 - x60*x66);
  *res_x = cx_ - ux + x28*x29;
  *res_y = cy_ - uy + x35*x63;
}
