// Auto-generated by gen_grad17_fisheye.py -- DO NOT EDIT BY HAND.
// OPENCV_FISHEYE, COLMAP +z convention, free principal point.
// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]
// at the perturbation origin. CSE over 34 gradient entries + 2 residuals.
#pragma once

__device__ __forceinline__ void FisheyeResidualGrad17(
    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,
    Scalar R20,Scalar R21,Scalar R22,
    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,
    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,
    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,
    Scalar ux,Scalar uy,
    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,
    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {
  Scalar x0 = R10*X0x + R11*X0y + R12*X0z;
  Scalar x1 = R00*X0x + R01*X0y + R02*X0z;
  Scalar x2 = t0x + x1;
  Scalar x3 = (x2*x2);
  Scalar x4 = R20*X0x + R21*X0y + R22*X0z;
  Scalar x5 = t0z + x4;
  Scalar x6 = (1.0/(x5*x5));
  Scalar x7 = x3*x6;
  Scalar x8 = t0y + x0;
  Scalar x9 = (x8*x8);
  Scalar x10 = x6*x9;
  Scalar x11 = x10 + x7;
  Scalar x12 = x11 + 1.0000000000000001e-32;
  Scalar x13 = sqrt(x12);
  Scalar x14 = 1.0/x13;
  Scalar x15 = atan(x13);
  Scalar x16 = (x15*x15);
  Scalar x17 = (x15*x15*x15*x15);
  Scalar x18 = pow(x15, 6);
  Scalar x19 = k1_*x16 + k2_*x17 + k3_*x18 + k4_*pow(x15, 8) + 1;
  Scalar x20 = x15*x19;
  Scalar x21 = x14*x20;
  Scalar x22 = x0*x21;
  Scalar x23 = 1/(x12*(x11 + 1.0));
  Scalar x24 = x19*x23;
  Scalar x25 = 1.0/x5;
  Scalar x26 = x0*x25;
  Scalar x27 = x26*x3 + x26*x9 + x4*x8;
  Scalar x28 = x25*x27;
  Scalar x29 = pow(x12, -3.0/2.0);
  Scalar x30 = 2*x16;
  Scalar x31 = x23*x30*(k1_ + k2_*x30 + 3*k3_*x17 + 4*k4_*x18);
  Scalar x32 = fx_*x2;
  Scalar x33 = x32*x6;
  Scalar x34 = x21*x4;
  Scalar x35 = x1*x25;
  Scalar x36 = x2*x21;
  Scalar x37 = x2*x4 + x3*x35 + x35*x9;
  Scalar x38 = x2*x6;
  Scalar x39 = x37*x38;
  Scalar x40 = x20*x29;
  Scalar x41 = fx_*x25;
  Scalar x42 = -x0*x2 + x1*x8;
  Scalar x43 = x38*x42;
  Scalar x44 = (x24 + x31 - x40)/(x5*x5*x5);
  Scalar x45 = x3 + x9;
  Scalar x46 = x45*x6;
  Scalar x47 = x15*x19*x29*x45*x6 - x21 - x24*x46 - x31*x46;
  Scalar x48 = x21*x25;
  Scalar x49 = x14*(x15*x15*x15);
  Scalar x50 = x2*x41;
  Scalar x51 = (x15*x15*x15*x15*x15);
  Scalar x52 = x14*x50;
  Scalar x53 = pow(x15, 7);
  Scalar x54 = pow(x15, 9);
  Scalar x55 = R20*x25;
  Scalar x56 = R00*x2 + R10*x8 - x3*x55 - x55*x9;
  Scalar x57 = x38*x56;
  Scalar x58 = R21*x25;
  Scalar x59 = R01*x2 + R11*x8 - x3*x58 - x58*x9;
  Scalar x60 = x38*x59;
  Scalar x61 = R22*x25;
  Scalar x62 = R02*x2 + R12*x8 - x3*x61 - x61*x9;
  Scalar x63 = x38*x62;
  Scalar x64 = x21*x8;
  Scalar x65 = x6*x8;
  Scalar x66 = x27*x65;
  Scalar x67 = fy_*x25;
  Scalar x68 = x1*x21;
  Scalar x69 = x25*x37;
  Scalar x70 = fy_*x8;
  Scalar x71 = x6*x70;
  Scalar x72 = x42*x65;
  Scalar x73 = x67*x8;
  Scalar x74 = x14*x73;
  Scalar x75 = x56*x65;
  Scalar x76 = x59*x65;
  Scalar x77 = x62*x65;
  grad_res_x[0] = x33*(x15*x19*x25*x27*x29 - x22 - x24*x28 - x28*x31);
  grad_res_x[1] = x41*(x24*x39 + x31*x39 + x34 + x35*x36 - x39*x40);
  grad_res_x[2] = x41*(-x22 + x24*x43 + x31*x43 - x40*x43);
  grad_res_x[3] = x41*(x21 + x24*x7 + x31*x7 - x40*x7);
  grad_res_x[4] = x32*x44*x8;
  grad_res_x[5] = x33*x47;
  grad_res_x[6] = x2*x48;
  grad_res_x[7] = 0;
  grad_res_x[8] = 1;
  grad_res_x[9] = 0;
  grad_res_x[10] = x49*x50;
  grad_res_x[11] = x51*x52;
  grad_res_x[12] = x52*x53;
  grad_res_x[13] = x52*x54;
  grad_res_x[14] = x41*(R00*x21 + x24*x57 + x31*x57 - x36*x55 - x40*x57);
  grad_res_x[15] = x41*(R01*x21 + x24*x60 + x31*x60 - x36*x58 - x40*x60);
  grad_res_x[16] = x41*(R02*x21 + x24*x63 + x31*x63 - x36*x61 - x40*x63);
  grad_res_y[0] = x67*(x15*x19*x27*x29*x6*x8 - x24*x66 - x26*x64 - x31*x66 - x34);
  grad_res_y[1] = x71*(x24*x69 + x31*x69 - x40*x69 + x68);
  grad_res_y[2] = x67*(x24*x72 + x31*x72 - x40*x72 + x68);
  grad_res_y[3] = x2*x44*x70;
  grad_res_y[4] = x67*(x10*x24 + x10*x31 - x10*x40 + x21);
  grad_res_y[5] = x47*x71;
  grad_res_y[6] = 0;
  grad_res_y[7] = x48*x8;
  grad_res_y[8] = 0;
  grad_res_y[9] = 1;
  grad_res_y[10] = x49*x73;
  grad_res_y[11] = x51*x74;
  grad_res_y[12] = x53*x74;
  grad_res_y[13] = x54*x74;
  grad_res_y[14] = x67*(R10*x21 + x24*x75 + x31*x75 - x40*x75 - x55*x64);
  grad_res_y[15] = x67*(R11*x21 + x24*x76 + x31*x76 - x40*x76 - x58*x64);
  grad_res_y[16] = x67*(R12*x21 + x24*x77 + x31*x77 - x40*x77 - x61*x64);
  *res_x = cx_ - ux + x21*x50;
  *res_y = cy_ - uy + x21*x73;
}
