# Auto-generated by gen_grad17_fisheye_atan2.py -- numpy twin of
# fisheye_grad17_atan2_generated.cuh (identical CSE temporaries).
import numpy as np
import math

def fisheye_residual_grad17_atan2(R00,R01,R02,R10,R11,R12,R20,R21,R22,
                            t0x,t0y,t0z,X0x,X0y,X0z,
                            fx_,fy_,cx_,cy_,k1_,k2_,k3_,k4_,ux,uy):
    x0 = R20*X0x + R21*X0y + R22*X0z
    x1 = R10*X0x + R11*X0y + R12*X0z
    x2 = t0y + x1
    x3 = R00*X0x + R01*X0y + R02*X0z
    x4 = t0x + x3
    x5 = x4**2
    x6 = x2**2
    x7 = x5 + x6 + 1.0e-32
    x8 = 1/x7
    x9 = math.sqrt(x7)
    x10 = t0z + x0
    x11 = math.atan2(x9, x10)
    x12 = x11**2
    x13 = x11**4
    x14 = x11**6
    x15 = k1_*x12 + k2_*x13 + k3_*x14 + k4_*x11**8 + 1
    x16 = 1/x9
    x17 = x10*x16
    x18 = x0*x17
    x19 = x1*x9 + x18*x2
    x20 = 1/(x10**2 + x7)
    x21 = x15*x20
    x22 = x19*x21
    x23 = 2*x12
    x24 = x23*(k1_ + k2_*x23 + 3*k3_*x13 + 4*k4_*x14)
    x25 = x20*x24
    x26 = x19*x25
    x27 = fx_*x16
    x28 = x27*x4
    x29 = x11*x15
    x30 = x0*x29
    x31 = x30*x8
    x32 = x18*x4 + x3*x9
    x33 = x21*x32
    x34 = x25*x32
    x35 = x16*x29
    x36 = -x1*x4 + x2*x3
    x37 = x29/x7**(3/2)
    x38 = x36*x37
    x39 = x10*x8
    x40 = x21*x39
    x41 = x36*x40
    x42 = x25*x39
    x43 = x36*x42
    x44 = fx_*x4
    x45 = x2*(-x37 + x40 + x42)
    x46 = x20*(x15 + x24)
    x47 = x11**3
    x48 = x11**5
    x49 = x11**7
    x50 = x11**9
    x51 = R00*x4 + R10*x2
    x52 = x29*x8
    x53 = x4*x52
    x54 = R20*x9 - x17*x51
    x55 = x21*x4
    x56 = x25*x4
    x57 = R01*x4 + R11*x2
    x58 = R21*x9 - x17*x57
    x59 = R02*x4 + R12*x2
    x60 = R22*x9 - x17*x59
    x61 = fy_*x16
    x62 = x2*x61
    x63 = fy_*x2
    x64 = x2*x52
    x65 = x2*x21
    x66 = x2*x25
    gx = [x28*(x0*x11*x15*x2*x8 - x22 - x26),
          x27*(x30 - x31*x5 + x33*x4 + x34*x4),
          fx_*(-x1*x35 - x38*x4 + x4*x41 + x4*x43),
          fx_*(x35 - x37*x5 + x40*x5 + x42*x5),
          x44*x45,
          -x44*x46,
          x35*x4,
          0,
          1,
          0,
          x28*x47,
          x28*x48,
          x28*x49,
          x28*x50,
          x27*(R00*x11*x15 - x51*x53 - x54*x55 - x54*x56),
          x27*(R01*x11*x15 - x53*x57 - x55*x58 - x56*x58),
          x27*(R02*x11*x15 - x53*x59 - x55*x60 - x56*x60)]
    gy = [x61*(x0*x11*x15*x6*x8 - x2*x22 - x2*x26 - x30),
          x62*(-x31*x4 + x33 + x34),
          fy_*(-x2*x38 + x2*x41 + x2*x43 + x3*x35),
          fy_*x4*x45,
          fy_*(x35 - x37*x6 + x40*x6 + x42*x6),
          -x46*x63,
          0,
          x2*x35,
          0,
          1,
          x47*x62,
          x48*x62,
          x49*x62,
          x50*x62,
          x61*(R10*x11*x15 - x51*x64 - x54*x65 - x54*x66),
          x61*(R11*x11*x15 - x57*x64 - x58*x65 - x58*x66),
          x61*(R12*x11*x15 - x59*x64 - x60*x65 - x60*x66)]
    rx = cx_ - ux + x28*x29
    ry = cy_ - uy + x35*x63
    return np.array(gx), np.array(gy), rx, ry
