#!/usr/bin/env python3
"""Smooth-domain twin of gen_grad17_fisheye.py: OPENCV_FISHEYE gradient with
theta = atan2(rho, Pz) instead of atan(rho/Pz).

Identical values and derivatives for Pz > 0, but no 1/Pz anywhere: the
residual and all 17 gradient columns stay finite and continuous through the
camera plane (theta = 90 deg) up to theta -> 180 deg. This is what lets the rig
path drop its 89.4-degree activity mask (see RFActive), whose hard boundary
turns the objective into a step function for rim observations: measured on
Fuchsberg ref300, LM steps that would lower the smooth cost by ~100 units are
rejected because a handful of rim observations cross the mask and jump by
their full r^2, the point damping ratchets to 1e7 and the solver reports
convergence 7% above the cost Ceres reaches on the same problem.

Same parameter order and retraction as the original:
    [dwx dwy dwz dtx dty dtz dfx dfy dcx dcy dk1 dk2 dk3 dk4 | dXx dXy dXz]
rho is regularized as sqrt(Px^2+Py^2+1e-32) (removable singularity on the
optical axis: theta/rho -> 1/Pz there).
"""
import sympy as sp
from gen_ccode import ccode  # sp.ccode with pow(x,n), |n|<=5, unrolled to products

dwx, dwy, dwz = sp.symbols('dwx dwy dwz', real=True)
dtx, dty, dtz = sp.symbols('dtx dty dtz', real=True)
dfx, dfy = sp.symbols('dfx dfy', real=True)
dcx, dcy = sp.symbols('dcx dcy', real=True)
dk1, dk2, dk3, dk4 = sp.symbols('dk1 dk2 dk3 dk4', real=True)
dXx, dXy, dXz = sp.symbols('dXx dXy dXz', real=True)
params = [dwx, dwy, dwz, dtx, dty, dtz,
          dfx, dfy, dcx, dcy, dk1, dk2, dk3, dk4,
          dXx, dXy, dXz]
NP = len(params)
assert NP == 17

R00,R01,R02,R10,R11,R12,R20,R21,R22 = sp.symbols(
    'R00 R01 R02 R10 R11 R12 R20 R21 R22', real=True)
R0 = sp.Matrix([[R00,R01,R02],[R10,R11,R12],[R20,R21,R22]])
t0x,t0y,t0z = sp.symbols('t0x t0y t0z', real=True); t0 = sp.Matrix([t0x,t0y,t0z])
X0x,X0y,X0z = sp.symbols('X0x X0y X0z', real=True); X0 = sp.Matrix([X0x,X0y,X0z])
fx_, fy_, cx_, cy_ = sp.symbols('fx_ fy_ cx_ cy_', real=True)
k1_, k2_, k3_, k4_ = sp.symbols('k1_ k2_ k3_ k4_', real=True)
ux, uy = sp.symbols('ux uy', real=True)

dw = sp.Matrix([dwx,dwy,dwz]); dt = sp.Matrix([dtx,dty,dtz]); dX = sp.Matrix([dXx,dXy,dXz])
def skew(v): return sp.Matrix([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
I3 = sp.eye(3); Skw = skew(dw)
ExpApprox = I3 + Skw + sp.Rational(1,2)*(Skw*Skw)

X = X0 + dX; t = t0 + dt
fx_cur = fx_ + dfx; fy_cur = fy_ + dfy
cx_cur = cx_ + dcx; cy_cur = cy_ + dcy
k1c = k1_ + dk1; k2c = k2_ + dk2; k3c = k3_ + dk3; k4c = k4_ + dk4

Pcam = ExpApprox*(R0*X) + t
Px,Py,Pz = Pcam[0],Pcam[1],Pcam[2]

# Same OPENCV_FISHEYE chain, parametrized by the incidence angle directly.
rho = sp.sqrt(Px*Px + Py*Py + sp.Float(1e-32))
theta = sp.atan2(rho, Pz)
s = theta/rho
uu = Px*s; vv = Py*s
th2 = theta*theta
radial = k1c*th2 + k2c*th2**2 + k3c*th2**3 + k4c*th2**4
d = 1 + radial
res_x = fx_cur*d*uu + cx_cur - ux
res_y = fy_cur*d*vv + cy_cur - uy

zero_subs = {p: 0 for p in params}
gx = [sp.diff(res_x, p).subs(zero_subs) for p in params]
gy = [sp.diff(res_y, p).subs(zero_subs) for p in params]
rx0 = res_x.subs(zero_subs); ry0 = res_y.subs(zero_subs)

repl, red = sp.cse(gx + gy + [rx0, ry0], optimizations='basic')

with open('fisheye_grad17_atan2_generated.cuh', 'w') as fh:
    fh.write('// Auto-generated by gen_grad17_fisheye_atan2.py -- DO NOT EDIT BY HAND.\n')
    fh.write('// OPENCV_FISHEYE, COLMAP +z convention, free principal point,\n')
    fh.write('// theta = atan2(rho, Pz): finite and smooth through the camera plane.\n')
    fh.write('// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]\n')
    fh.write('// at the perturbation origin. CSE over 34 gradient entries + 2 residuals.\n')
    fh.write('#pragma once\n\n')
    fh.write('__device__ __forceinline__ void FisheyeResidualGrad17A(\n')
    fh.write('    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,\n')
    fh.write('    Scalar R20,Scalar R21,Scalar R22,\n')
    fh.write('    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,\n')
    fh.write('    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,\n')
    fh.write('    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,\n')
    fh.write('    Scalar ux,Scalar uy,\n')
    fh.write('    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,\n')
    fh.write('    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {\n')
    for sym, expr in repl: fh.write(f'  Scalar {sym} = {ccode(expr)};\n')
    for i, e in enumerate(red[0:NP]):      fh.write(f'  grad_res_x[{i}] = {ccode(e)};\n')
    for i, e in enumerate(red[NP:2*NP]):   fh.write(f'  grad_res_y[{i}] = {ccode(e)};\n')
    fh.write(f'  *res_x = {ccode(red[2*NP])};\n')
    fh.write(f'  *res_y = {ccode(red[2*NP+1])};\n')
    fh.write('}\n')
print('temporaries:', len(repl))

with open('fisheye_grad17_atan2_numpy.py', 'w') as fh:
    fh.write('# Auto-generated by gen_grad17_fisheye_atan2.py -- numpy twin of\n')
    fh.write('# fisheye_grad17_atan2_generated.cuh (identical CSE temporaries).\n')
    fh.write('import numpy as np\nimport math\n\n')
    fh.write('def fisheye_residual_grad17_atan2(R00,R01,R02,R10,R11,R12,R20,R21,R22,\n')
    fh.write('                            t0x,t0y,t0z,X0x,X0y,X0z,\n')
    fh.write('                            fx_,fy_,cx_,cy_,k1_,k2_,k3_,k4_,ux,uy):\n')
    for sym, expr in repl:
        fh.write(f'    {sym} = {sp.pycode(expr)}\n')
    fh.write('    gx = [' + ',\n          '.join(sp.pycode(e) for e in red[0:NP]) + ']\n')
    fh.write('    gy = [' + ',\n          '.join(sp.pycode(e) for e in red[NP:2*NP]) + ']\n')
    fh.write(f'    rx = {sp.pycode(red[2*NP])}\n')
    fh.write(f'    ry = {sp.pycode(red[2*NP+1])}\n')
    fh.write('    return np.array(gx), np.array(gy), rx, ry\n')
print('wrote fisheye_grad17_atan2_generated.cuh and fisheye_grad17_atan2_numpy.py')
