#!/usr/bin/env python3
"""Round 10: 12-parameter grad-only codegen for the 9-DOF-camera port.

Identical symbolic derivation to mfree_r9/solver/gen_gradonly.py (same SO(3)
second-order retraction, same BAL residual), but the perturbation vector now
includes the three intrinsics: param order

    [dwx, dwy, dwz, dtx, dty, dtz, df, dk1, dk2 | dXx, dXy, dXz]

i.e. camera block = 9 (pose 6 + intrinsics 3), point block = 3. Intrinsics
retract additively: f = f0 + df, k1 = k10 + dk1, k2 = k20 + dk2.

Grad-only on purpose: the matrix-free solver (MFAssemble) consumes ONLY the
per-residual gradients (Gauss-Newton products g_i*g_j); the 144-entry true
Hessian would defeat nvcc's dead-code elimination (round 9 measured that the
6-DOF kernel's 96-register/0-spill budget exists only because 45 of 81 entries
are DCE'd away).
"""
import sympy as sp

dwx, dwy, dwz = sp.symbols('dwx dwy dwz', real=True)
dtx, dty, dtz = sp.symbols('dtx dty dtz', real=True)
df, dk1, dk2 = sp.symbols('df dk1 dk2', real=True)
dXx, dXy, dXz = sp.symbols('dXx dXy dXz', real=True)
params = [dwx, dwy, dwz, dtx, dty, dtz, df, dk1, dk2, dXx, dXy, dXz]
NP = len(params)
R00,R01,R02,R10,R11,R12,R20,R21,R22 = sp.symbols('R00 R01 R02 R10 R11 R12 R20 R21 R22', real=True)
R0 = sp.Matrix([[R00,R01,R02],[R10,R11,R12],[R20,R21,R22]])
t0x,t0y,t0z = sp.symbols('t0x t0y t0z', real=True); t0 = sp.Matrix([t0x,t0y,t0z])
X0x,X0y,X0z = sp.symbols('X0x X0y X0z', real=True); X0 = sp.Matrix([X0x,X0y,X0z])
f_, k1_, k2_ = sp.symbols('f_ k1_ k2_', real=True)
ux, uy = sp.symbols('ux uy', real=True)
dw = sp.Matrix([dwx,dwy,dwz]); dt = sp.Matrix([dtx,dty,dtz]); dX = sp.Matrix([dXx,dXy,dXz])
def skew(v): return sp.Matrix([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
I3 = sp.eye(3); Skw = skew(dw)
ExpApprox = I3 + Skw + sp.Rational(1,2)*(Skw*Skw)
X = X0 + dX; t = t0 + dt
f_cur = f_ + df; k1_cur = k1_ + dk1; k2_cur = k2_ + dk2
Pcam = ExpApprox*(R0*X) + t
Px,Py,Pz = Pcam[0],Pcam[1],Pcam[2]
xp = -Px/Pz; yp = -Py/Pz
r2 = xp*xp + yp*yp
dist = 1 + k1_cur*r2 + k2_cur*r2*r2
res_x = f_cur*dist*xp - ux
res_y = f_cur*dist*yp - uy
zero_subs = {s: 0 for s in params}
gx = [sp.diff(res_x, p).subs(zero_subs) for p in params]
gy = [sp.diff(res_y, p).subs(zero_subs) for p in params]
rx0 = res_x.subs(zero_subs); ry0 = res_y.subs(zero_subs)
repl, red = sp.cse(gx + gy + [rx0, ry0], optimizations='basic')
with open('bal_grad12_generated.cuh', 'w') as fh:
    fh.write('// Auto-generated by gen_grad12.py -- DO NOT EDIT BY HAND.\n')
    fh.write('// 12-parameter Gauss-Newton specialization: per-residual gradients over\n')
    fh.write('// [dwx,dwy,dwz,dtx,dty,dtz,df,dk1,dk2,dXx,dXy,dXz] at the perturbation\n')
    fh.write('// origin. CSE over the 24 gradient entries + 2 residuals only.\n#pragma once\n\n')
    fh.write('__device__ __forceinline__ void BalResidualGrad12(\n')
    fh.write('    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,\n')
    fh.write('    Scalar R20,Scalar R21,Scalar R22,\n')
    fh.write('    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,\n')
    fh.write('    Scalar f_,Scalar k1_,Scalar k2_,Scalar ux,Scalar uy,\n')
    fh.write('    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,\n')
    fh.write('    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {\n')
    for sym, expr in repl: fh.write(f'  Scalar {sym} = {sp.ccode(expr)};\n')
    for i, e in enumerate(red[0:NP]):      fh.write(f'  grad_res_x[{i}] = {sp.ccode(e)};\n')
    for i, e in enumerate(red[NP:2*NP]):   fh.write(f'  grad_res_y[{i}] = {sp.ccode(e)};\n')
    fh.write(f'  *res_x = {sp.ccode(red[2*NP])};\n')
    fh.write(f'  *res_y = {sp.ccode(red[2*NP+1])};\n')
    fh.write('}\n')
print('temporaries:', len(repl))

# ---- also emit a numpy twin of the SAME cse'd expressions for validation ----
with open('bal_grad12_numpy.py', 'w') as fh:
    fh.write('# Auto-generated by gen_grad12.py -- numpy twin of bal_grad12_generated.cuh\n')
    fh.write('# (identical CSE temporaries, so FD validation exercises the shipped formula).\n')
    fh.write('import numpy as np\n\n')
    fh.write('def bal_residual_grad12(R00,R01,R02,R10,R11,R12,R20,R21,R22,\n')
    fh.write('                        t0x,t0y,t0z,X0x,X0y,X0z,f_,k1_,k2_,ux,uy):\n')
    for sym, expr in repl:
        fh.write(f'    {sym} = {sp.pycode(expr)}\n')
    fh.write('    gx = [' + ',\n          '.join(sp.pycode(e) for e in red[0:NP]) + ']\n')
    fh.write('    gy = [' + ',\n          '.join(sp.pycode(e) for e in red[NP:2*NP]) + ']\n')
    fh.write(f'    rx = {sp.pycode(red[2*NP])}\n')
    fh.write(f'    ry = {sp.pycode(red[2*NP+1])}\n')
    fh.write('    return np.array(gx), np.array(gy), rx, ry\n')
print('wrote bal_grad12_generated.cuh and bal_grad12_numpy.py')
