#!/usr/bin/env python3
"""Pinhole/radial twin of gen_grad17_fisheye_atan2.py.

Same 17-column tangent layout and the same 8-slot intrinsics vector
[fx fy cx cy k1 k2 k3 k4] as the fisheye kernels, so the rig solver can switch
projection model per calibration group without touching its storage contract:

    x = Px/Pz, y = Py/Pz, r2 = x^2 + y^2
    d = 1 + k1 r2 + k2 r2^2            (k3, k4 unused: their columns are 0)
    res = (fx d x + cx - u, fy d y + cy - v)

Covers COLMAP's SIMPLE_PINHOLE / PINHOLE (k1=k2=0, columns masked off by the
caller), SIMPLE_RADIAL (k1) and RADIAL (k1, k2). The SIMPLE_* models tie
fx=fy; the caller keeps them equal by masking dfy and copying fx on write-back.
"""
import sympy as sp
from gen_ccode import ccode  # sp.ccode with pow(x,n), |n|<=5, unrolled to products

dwx, dwy, dwz = sp.symbols('dwx dwy dwz', real=True)
dtx, dty, dtz = sp.symbols('dtx dty dtz', real=True)
dfx, dfy = sp.symbols('dfx dfy', real=True)
dcx, dcy = sp.symbols('dcx dcy', real=True)
dk1, dk2, dk3, dk4 = sp.symbols('dk1 dk2 dk3 dk4', real=True)
dXx, dXy, dXz = sp.symbols('dXx dXy dXz', real=True)
params = [dwx, dwy, dwz, dtx, dty, dtz,
          dfx, dfy, dcx, dcy, dk1, dk2, dk3, dk4,
          dXx, dXy, dXz]
NP = len(params)
assert NP == 17

R00,R01,R02,R10,R11,R12,R20,R21,R22 = sp.symbols(
    'R00 R01 R02 R10 R11 R12 R20 R21 R22', real=True)
R0 = sp.Matrix([[R00,R01,R02],[R10,R11,R12],[R20,R21,R22]])
t0x,t0y,t0z = sp.symbols('t0x t0y t0z', real=True); t0 = sp.Matrix([t0x,t0y,t0z])
X0x,X0y,X0z = sp.symbols('X0x X0y X0z', real=True); X0 = sp.Matrix([X0x,X0y,X0z])
fx_, fy_, cx_, cy_ = sp.symbols('fx_ fy_ cx_ cy_', real=True)
k1_, k2_, k3_, k4_ = sp.symbols('k1_ k2_ k3_ k4_', real=True)
ux, uy = sp.symbols('ux uy', real=True)

dw = sp.Matrix([dwx,dwy,dwz]); dt = sp.Matrix([dtx,dty,dtz]); dX = sp.Matrix([dXx,dXy,dXz])
def skew(v): return sp.Matrix([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
I3 = sp.eye(3); Skw = skew(dw)
ExpApprox = I3 + Skw + sp.Rational(1,2)*(Skw*Skw)

X = X0 + dX; t = t0 + dt
fx_cur = fx_ + dfx; fy_cur = fy_ + dfy
cx_cur = cx_ + dcx; cy_cur = cy_ + dcy
k1c = k1_ + dk1; k2c = k2_ + dk2

Pcam = ExpApprox*(R0*X) + t
Px,Py,Pz = Pcam[0],Pcam[1],Pcam[2]

xn = Px/Pz; yn = Py/Pz
r2 = xn*xn + yn*yn
d = 1 + k1c*r2 + k2c*r2**2
res_x = fx_cur*d*xn + cx_cur - ux
res_y = fy_cur*d*yn + cy_cur - uy

zero_subs = {p: 0 for p in params}
gx = [sp.diff(res_x, p).subs(zero_subs) for p in params]
gy = [sp.diff(res_y, p).subs(zero_subs) for p in params]
rx0 = res_x.subs(zero_subs); ry0 = res_y.subs(zero_subs)

repl, red = sp.cse(gx + gy + [rx0, ry0], optimizations='basic')

with open('pinhole_grad17_generated.cuh', 'w') as fh:
    fh.write('// Auto-generated by gen_grad17_pinhole.py -- DO NOT EDIT BY HAND.\n')
    fh.write('// Pinhole + polynomial radial distortion (COLMAP SIMPLE_PINHOLE, PINHOLE,\n')
    fh.write('// SIMPLE_RADIAL, RADIAL), +z convention, free principal point.\n')
    fh.write('// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]\n')
    fh.write('// at the perturbation origin; dk3/dk4 columns are identically 0.\n')
    fh.write('#pragma once\n\n')
    fh.write('__device__ __forceinline__ void PinholeResidualGrad17(\n')
    fh.write('    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,\n')
    fh.write('    Scalar R20,Scalar R21,Scalar R22,\n')
    fh.write('    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,\n')
    fh.write('    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,\n')
    fh.write('    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,\n')
    fh.write('    Scalar ux,Scalar uy,\n')
    fh.write('    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,\n')
    fh.write('    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {\n')
    fh.write('  (void)k3_; (void)k4_;\n')
    for sym, expr in repl: fh.write(f'  Scalar {sym} = {ccode(expr)};\n')
    for i, e in enumerate(red[0:NP]):      fh.write(f'  grad_res_x[{i}] = {ccode(e)};\n')
    for i, e in enumerate(red[NP:2*NP]):   fh.write(f'  grad_res_y[{i}] = {ccode(e)};\n')
    fh.write(f'  *res_x = {ccode(red[2*NP])};\n')
    fh.write(f'  *res_y = {ccode(red[2*NP+1])};\n')
    fh.write('}\n')
print('temporaries:', len(repl))

with open('pinhole_grad17_numpy.py', 'w') as fh:
    fh.write('# Auto-generated by gen_grad17_pinhole.py -- numpy twin of\n')
    fh.write('# pinhole_grad17_generated.cuh (identical CSE temporaries).\n')
    fh.write('import numpy as np\nimport math\n\n')
    fh.write('def pinhole_residual_grad17(R00,R01,R02,R10,R11,R12,R20,R21,R22,\n')
    fh.write('                            t0x,t0y,t0z,X0x,X0y,X0z,\n')
    fh.write('                            fx_,fy_,cx_,cy_,k1_,k2_,k3_,k4_,ux,uy):\n')
    for sym, expr in repl:
        fh.write(f'    {sym} = {sp.pycode(expr)}\n')
    fh.write('    gx = [' + ',\n          '.join(sp.pycode(e) for e in red[0:NP]) + ']\n')
    fh.write('    gy = [' + ',\n          '.join(sp.pycode(e) for e in red[NP:2*NP]) + ']\n')
    fh.write(f'    rx = {sp.pycode(red[2*NP])}\n')
    fh.write(f'    ry = {sp.pycode(red[2*NP+1])}\n')
    fh.write('    return np.array(gx), np.array(gy), rx, ry\n')
print('wrote pinhole_grad17_generated.cuh and pinhole_grad17_numpy.py')
