#!/usr/bin/env python3
"""Round 12: 17-parameter grad-only codegen for the OPENCV_FISHEYE + rig port.

Same derivation style as gen_grad12.py (SO(3) second-order retraction via the
truncated exponential, additive intrinsics/translation/point perturbations,
grad-only CSE), but three deliberate differences:

  * COLMAP-native +z convention. The BAL kernels look down -z and the COLMAP
    adapter conjugates with D=diag(1,-1,-1); this path instead generates the
    residual directly in COLMAP's frame so the adapter passes R, t, and raw
    pixel observations through untouched. Two conventions coexist in
    oca_cuda.cu but never mix: BAL kernels consume BalResidualGrad12, the
    fisheye kernels consume FisheyeResidualGrad17.

  * OPENCV_FISHEYE residual, matching colmap/src/colmap/sensor/models.h
    exactly: normalize u=x/z, v=y/z; theta=atan(r); scale by theta/r;
    radial = k1 th^2 + k2 th^4 + k3 th^6 + k4 th^8 applied as (1+radial);
    then fx,fy,cx,cy. COLMAP guards z>0 (HasProjectableDepth), and fisheye
    masks in practice keep theta < 90 deg, so normalize-first is valid and
    cheirality remains z>0.

  * The principal point is a free column (dcx,dcy): unlike the BAL path the
    adapter must NOT bake cx,cy into the observations.

The rig does not appear here on purpose. Differentiation is w.r.t. the IMAGE
pose tangent; with cam = sensor_from_rig o rig_from_world and the retraction
R <- exp(dw) R, t <- t + dt, a frame perturbation maps to the image tangent as
dw_cam = R_S dw_frame, dt_cam = R_S dt_frame (exactly, not just first order),
so rig sharing is a tangent-space linear constraint applied outside this
kernel by broadcast/reduce -- the same architecture as round 11's calibration
groups, with 3x3 rotation blocks instead of 0/1 entries.

Param order:
    [dwx dwy dwz dtx dty dtz dfx dfy dcx dcy dk1 dk2 dk3 dk4 | dXx dXy dXz]

r is regularized as sqrt(nu^2+nv^2+1e-32): the exact expressions have a
removable singularity at the principal axis (theta/r -> 1); 1e-32 moves
nothing at the r ~ 0.1..1.8 range of real fisheye data but keeps the
generated code finite if an observation lands exactly on the axis.
"""
import sympy as sp

dwx, dwy, dwz = sp.symbols('dwx dwy dwz', real=True)
dtx, dty, dtz = sp.symbols('dtx dty dtz', real=True)
dfx, dfy = sp.symbols('dfx dfy', real=True)
dcx, dcy = sp.symbols('dcx dcy', real=True)
dk1, dk2, dk3, dk4 = sp.symbols('dk1 dk2 dk3 dk4', real=True)
dXx, dXy, dXz = sp.symbols('dXx dXy dXz', real=True)
params = [dwx, dwy, dwz, dtx, dty, dtz,
          dfx, dfy, dcx, dcy, dk1, dk2, dk3, dk4,
          dXx, dXy, dXz]
NP = len(params)
assert NP == 17

R00,R01,R02,R10,R11,R12,R20,R21,R22 = sp.symbols(
    'R00 R01 R02 R10 R11 R12 R20 R21 R22', real=True)
R0 = sp.Matrix([[R00,R01,R02],[R10,R11,R12],[R20,R21,R22]])
t0x,t0y,t0z = sp.symbols('t0x t0y t0z', real=True); t0 = sp.Matrix([t0x,t0y,t0z])
X0x,X0y,X0z = sp.symbols('X0x X0y X0z', real=True); X0 = sp.Matrix([X0x,X0y,X0z])
fx_, fy_, cx_, cy_ = sp.symbols('fx_ fy_ cx_ cy_', real=True)
k1_, k2_, k3_, k4_ = sp.symbols('k1_ k2_ k3_ k4_', real=True)
ux, uy = sp.symbols('ux uy', real=True)

dw = sp.Matrix([dwx,dwy,dwz]); dt = sp.Matrix([dtx,dty,dtz]); dX = sp.Matrix([dXx,dXy,dXz])
def skew(v): return sp.Matrix([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
I3 = sp.eye(3); Skw = skew(dw)
ExpApprox = I3 + Skw + sp.Rational(1,2)*(Skw*Skw)

X = X0 + dX; t = t0 + dt
fx_cur = fx_ + dfx; fy_cur = fy_ + dfy
cx_cur = cx_ + dcx; cy_cur = cy_ + dcy
k1c = k1_ + dk1; k2c = k2_ + dk2; k3c = k3_ + dk3; k4c = k4_ + dk4

Pcam = ExpApprox*(R0*X) + t
Px,Py,Pz = Pcam[0],Pcam[1],Pcam[2]

# COLMAP OPENCV_FISHEYE forward chain, +z.
nu = Px/Pz; nv = Py/Pz
r = sp.sqrt(nu*nu + nv*nv + sp.Float(1e-32))
theta = sp.atan(r)
s = theta/r
uu = nu*s; vv = nv*s
th2 = theta*theta
radial = k1c*th2 + k2c*th2**2 + k3c*th2**3 + k4c*th2**4
d = 1 + radial
res_x = fx_cur*d*uu + cx_cur - ux
res_y = fy_cur*d*vv + cy_cur - uy

zero_subs = {p: 0 for p in params}
gx = [sp.diff(res_x, p).subs(zero_subs) for p in params]
gy = [sp.diff(res_y, p).subs(zero_subs) for p in params]
rx0 = res_x.subs(zero_subs); ry0 = res_y.subs(zero_subs)

repl, red = sp.cse(gx + gy + [rx0, ry0], optimizations='basic')

with open('fisheye_grad17_generated.cuh', 'w') as fh:
    fh.write('// Auto-generated by gen_grad17_fisheye.py -- DO NOT EDIT BY HAND.\n')
    fh.write('// OPENCV_FISHEYE, COLMAP +z convention, free principal point.\n')
    fh.write('// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]\n')
    fh.write('// at the perturbation origin. CSE over 34 gradient entries + 2 residuals.\n')
    fh.write('#pragma once\n\n')
    fh.write('__device__ __forceinline__ void FisheyeResidualGrad17(\n')
    fh.write('    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,\n')
    fh.write('    Scalar R20,Scalar R21,Scalar R22,\n')
    fh.write('    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,\n')
    fh.write('    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,\n')
    fh.write('    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,\n')
    fh.write('    Scalar ux,Scalar uy,\n')
    fh.write('    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,\n')
    fh.write('    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {\n')
    for sym, expr in repl: fh.write(f'  Scalar {sym} = {sp.ccode(expr)};\n')
    for i, e in enumerate(red[0:NP]):      fh.write(f'  grad_res_x[{i}] = {sp.ccode(e)};\n')
    for i, e in enumerate(red[NP:2*NP]):   fh.write(f'  grad_res_y[{i}] = {sp.ccode(e)};\n')
    fh.write(f'  *res_x = {sp.ccode(red[2*NP])};\n')
    fh.write(f'  *res_y = {sp.ccode(red[2*NP+1])};\n')
    fh.write('}\n')
print('temporaries:', len(repl))

with open('fisheye_grad17_numpy.py', 'w') as fh:
    fh.write('# Auto-generated by gen_grad17_fisheye.py -- numpy twin of\n')
    fh.write('# fisheye_grad17_generated.cuh (identical CSE temporaries, so FD\n')
    fh.write('# validation exercises the shipped formula).\n')
    fh.write('import numpy as np\nimport math\n\n')
    fh.write('def fisheye_residual_grad17(R00,R01,R02,R10,R11,R12,R20,R21,R22,\n')
    fh.write('                            t0x,t0y,t0z,X0x,X0y,X0z,\n')
    fh.write('                            fx_,fy_,cx_,cy_,k1_,k2_,k3_,k4_,ux,uy):\n')
    for sym, expr in repl:
        fh.write(f'    {sym} = {sp.pycode(expr)}\n')
    fh.write('    gx = [' + ',\n          '.join(sp.pycode(e) for e in red[0:NP]) + ']\n')
    fh.write('    gy = [' + ',\n          '.join(sp.pycode(e) for e in red[NP:2*NP]) + ']\n')
    fh.write(f'    rx = {sp.pycode(red[2*NP])}\n')
    fh.write(f'    ry = {sp.pycode(red[2*NP+1])}\n')
    fh.write('    return np.array(gx), np.array(gy), rx, ry\n')
print('wrote fisheye_grad17_generated.cuh and fisheye_grad17_numpy.py')
