// Auto-generated by gen_grad17_pinhole.py -- DO NOT EDIT BY HAND.
// Pinhole + polynomial radial distortion (COLMAP SIMPLE_PINHOLE, PINHOLE,
// SIMPLE_RADIAL, RADIAL), +z convention, free principal point.
// Per-residual gradients over [dw3 dt3 dfx dfy dcx dcy dk1..dk4 | dX3]
// at the perturbation origin; dk3/dk4 columns are identically 0.
#pragma once

__device__ __forceinline__ void PinholeResidualGrad17(
    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,
    Scalar R20,Scalar R21,Scalar R22,
    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,
    Scalar fx_,Scalar fy_,Scalar cx_,Scalar cy_,
    Scalar k1_,Scalar k2_,Scalar k3_,Scalar k4_,
    Scalar ux,Scalar uy,
    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,
    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {
  (void)k3_; (void)k4_;
  Scalar x0 = R10*X0x + R11*X0y + R12*X0z;
  Scalar x1 = R20*X0x + R21*X0y + R22*X0z;
  Scalar x2 = t0z + x1;
  Scalar x3 = (1.0/(x2*x2));
  Scalar x4 = R00*X0x + R01*X0y + R02*X0z;
  Scalar x5 = t0x + x4;
  Scalar x6 = (x5*x5);
  Scalar x7 = t0y + x0;
  Scalar x8 = (x7*x7);
  Scalar x9 = x6 + x8;
  Scalar x10 = x3*x9;
  Scalar x11 = (x9*x9);
  Scalar x12 = k1_*x10 + k2_*x11/(x2*x2*x2*x2) + 1;
  Scalar x13 = x0*x12;
  Scalar x14 = 1.0/x2;
  Scalar x15 = x0*x14;
  Scalar x16 = x1*x7 + x15*x6 + x15*x8;
  Scalar x17 = 2*x10;
  Scalar x18 = k1_ + k2_*x17;
  Scalar x19 = 2*x18;
  Scalar x20 = x14*x19;
  Scalar x21 = fx_*x5;
  Scalar x22 = x21*x3;
  Scalar x23 = x1*x12;
  Scalar x24 = x12*x4;
  Scalar x25 = x14*x4;
  Scalar x26 = x1*x5 + x25*x6 + x25*x8;
  Scalar x27 = x19*x3;
  Scalar x28 = x27*x5;
  Scalar x29 = fx_*x14;
  Scalar x30 = -x0*x5 + x4*x7;
  Scalar x31 = (1.0/(x2*x2*x2));
  Scalar x32 = x19*x31;
  Scalar x33 = x12 + x17*x18;
  Scalar x34 = x12*x14;
  Scalar x35 = x34*x5;
  Scalar x36 = x31*x9;
  Scalar x37 = x11/(x2*x2*x2*x2*x2);
  Scalar x38 = R20*x14;
  Scalar x39 = R00*x5 + R10*x7 - x38*x6 - x38*x8;
  Scalar x40 = R21*x14;
  Scalar x41 = R01*x5 + R11*x7 - x40*x6 - x40*x8;
  Scalar x42 = R22*x14;
  Scalar x43 = R02*x5 + R12*x7 - x42*x6 - x42*x8;
  Scalar x44 = x27*x7;
  Scalar x45 = fy_*x14;
  Scalar x46 = fy_*x7;
  Scalar x47 = x3*x46;
  Scalar x48 = x34*x7;
  grad_res_x[0] = -x22*(x13 + x16*x20);
  grad_res_x[1] = x29*(x14*x24*x5 + x23 + x26*x28);
  grad_res_x[2] = x29*(-x13 + x28*x30);
  grad_res_x[3] = x29*(x12 + x27*x6);
  grad_res_x[4] = x21*x32*x7;
  grad_res_x[5] = -x22*x33;
  grad_res_x[6] = x35;
  grad_res_x[7] = 0;
  grad_res_x[8] = 1;
  grad_res_x[9] = 0;
  grad_res_x[10] = x21*x36;
  grad_res_x[11] = x21*x37;
  grad_res_x[12] = 0;
  grad_res_x[13] = 0;
  grad_res_x[14] = x29*(R00*x12 - R20*x35 + x28*x39);
  grad_res_x[15] = x29*(R01*x12 - R21*x35 + x28*x41);
  grad_res_x[16] = x29*(R02*x12 - R22*x35 + x28*x43);
  grad_res_y[0] = -x45*(x13*x14*x7 + x16*x44 + x23);
  grad_res_y[1] = x47*(x20*x26 + x24);
  grad_res_y[2] = x45*(x24 + x30*x44);
  grad_res_y[3] = x32*x46*x5;
  grad_res_y[4] = x45*(x12 + x27*x8);
  grad_res_y[5] = -x33*x47;
  grad_res_y[6] = 0;
  grad_res_y[7] = x48;
  grad_res_y[8] = 0;
  grad_res_y[9] = 1;
  grad_res_y[10] = x36*x46;
  grad_res_y[11] = x37*x46;
  grad_res_y[12] = 0;
  grad_res_y[13] = 0;
  grad_res_y[14] = x45*(R10*x12 - R20*x48 + x39*x44);
  grad_res_y[15] = x45*(R11*x12 - R21*x48 + x41*x44);
  grad_res_y[16] = x45*(R12*x12 - R22*x48 + x43*x44);
  *res_x = cx_ - ux + x12*x29*x5;
  *res_y = cy_ + fy_*x48 - uy;
}
