#include <cuda_runtime.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <random>
#include <stdexcept>
#include <string>
#include <vector>
using Scalar=double;
#define CK(x) do{cudaError_t e=(x);if(e!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(e));}while(0)
template<class T>T* Load(const std::string&p,size_t n,std::vector<T>*host=nullptr){std::vector<T> h(n);FILE*f=fopen(p.c_str(),"rb");if(!f||fread(h.data(),sizeof(T),n,f)!=n)throw std::runtime_error("read "+p);fclose(f);T*d=nullptr;CK(cudaMalloc(&d,n*sizeof(T)));CK(cudaMemcpy(d,h.data(),n*sizeof(T),cudaMemcpyHostToDevice));if(host)*host=std::move(h);return d;}
template<class T>T* Alloc(size_t n){T*d=nullptr;CK(cudaMalloc(&d,n*sizeof(T)));return d;}
__device__ __forceinline__ void Vinv(const double*R,const double*t,double*u){double y0=t[0]/R[0],y1=(t[1]-R[1]*y0)/R[3],y2=(t[2]-R[2]*y0-R[4]*y1)/R[5];u[2]=y2/R[5];u[1]=(y1-R[4]*u[2])/R[3];u[0]=(y0-R[1]*u[1]-R[2]*u[2])/R[0];}
__global__ void PointPass1(const float*G,const int*poff,const int*order,const int*cams,const double*v,int np,int no,double*t){int p=blockIdx.x,w=threadIdx.x>>5,l=threadIdx.x&31;if(p>=np||w)return;double a[3]={};for(int q=poff[p]+l;q<poff[p+1];q+=32){int k=order[q];const double*vc=v+9*cams[k];for(int j=0;j<3;++j)for(int i=0;i<9;++i)a[j]+=(double)G[(size_t)(3*i+j)*no+k]*vc[i];}for(int d=16;d;d>>=1)for(int j=0;j<3;++j)a[j]+=__shfl_down_sync(~0u,a[j],d);if(!l){t[3*p]=a[0];t[3*p+1]=a[1];t[3*p+2]=a[2];}}
__global__ void ApplyVinv(const double*R,const double*t,int np,double*u){int p=blockIdx.x*blockDim.x+threadIdx.x;if(p>=np)return;const double*r=R+6*p;if(!(r[0]>0&&r[3]>0&&r[5]>0))u[3*p]=u[3*p+1]=u[3*p+2]=0;else Vinv(r,t+3*p,u+3*p);}
__global__ void Fused(const float*G,const int*poff,const int*order,const int*cams,const double*v,const double*R,int np,int no,double*u){int w=threadIdx.x>>5,l=threadIdx.x&31,p=blockIdx.x*4+w;if(p>=np)return;double a[3]={};for(int q=poff[p]+l;q<poff[p+1];q+=32){int k=order[q];const double*vc=v+9*cams[k];for(int j=0;j<3;++j)for(int i=0;i<9;++i)a[j]+=(double)G[(size_t)(3*i+j)*no+k]*vc[i];}for(int d=16;d;d>>=1)for(int j=0;j<3;++j)a[j]+=__shfl_down_sync(~0u,a[j],d);if(!l){const double*r=R+6*p;if(!(r[0]>0&&r[3]>0&&r[5]>0))u[3*p]=u[3*p+1]=u[3*p+2]=0;else Vinv(r,a,u+3*p);}}
__global__ void Schur(const float*G,const int*pt,const int*coff,const double*U,const double*v,const double*u,int nc,int no,double*out){int c=blockIdx.x;if(c>=nc)return;for(int i=threadIdx.x;i<9;i+=blockDim.x){double z=0;for(int j=0;j<9;++j)z+=U[81ul*c+9*i+j]*v[9*c+j];for(int k=coff[c];k<coff[c+1];++k)for(int j=0;j<3;++j)z-=(double)G[(size_t)(3*i+j)*no+k]*u[3*pt[k]+j];out[9*c+i]=z;}}
double Norm(const std::vector<double>&x){long double s=0;for(double v:x)s+=(long double)v*v;return std::sqrt((double)s);}double Dot(const std::vector<double>&a,const std::vector<double>&b){long double s=0;for(size_t i=0;i<a.size();++i)s+=(long double)a[i]*b[i];return(double)s;}
int main(int ac,char**av){try{if(ac!=2)return 2;std::string d=std::string(av[1])+"/";int cd,nc,np,no;double sig,rad,eta;FILE*f=fopen((d+"dimensions.txt").c_str(),"r");if(!f||fscanf(f,"%d%d%d%d%lf%lf%lf",&cd,&nc,&np,&no,&sig,&rad,&eta)!=7||cd!=9)return 2;fclose(f);
 std::vector<int> hp,hc,hco;float*G=Load<float>(d+"W",27ul*no);double*R=Load<double>(d+"R",6ul*np);double*U=Load<double>(d+"U",81ul*nc);int*pt=Load<int>(d+"points",no,&hp);int*cam=Load<int>(d+"cams",no,&hc);int*coff=Load<int>(d+"offsets",nc+1,&hco);std::vector<int> poff(np+1),order(no),cur;for(int p:hp)++poff[p+1];for(int p=0;p<np;++p)poff[p+1]+=poff[p];cur=poff;for(int k=0;k<no;++k)order[cur[hp[k]]++]=k;int *dpo=Alloc<int>(np+1),*dor=Alloc<int>(no);CK(cudaMemcpy(dpo,poff.data(),(np+1)*4,cudaMemcpyHostToDevice));CK(cudaMemcpy(dor,order.data(),no*4,cudaMemcpyHostToDevice));double *v=Alloc<double>(9ul*nc),*t=Alloc<double>(3ul*np),*ub=Alloc<double>(3ul*np),*uf=Alloc<double>(3ul*np),*sb=Alloc<double>(9ul*nc),*sf=Alloc<double>(9ul*nc);cudaEvent_t a,b;cudaEventCreate(&a);cudaEventCreate(&b);
 for(int seed=1701;seed<=1703;++seed){std::mt19937_64 gen(seed);std::normal_distribution<double>nd;for(int probe=0;probe<4;++probe){std::vector<double>hv(9ul*nc);for(double&x:hv)x=nd(gen);CK(cudaMemcpy(v,hv.data(),hv.size()*8,cudaMemcpyHostToDevice));CK(cudaMemset(t,0,3ul*np*8));PointPass1<<<np,32>>>(G,dpo,dor,cam,v,np,no,t);ApplyVinv<<<(np+255)/256,256>>>(R,t,np,ub);Fused<<<(np+3)/4,128>>>(G,dpo,dor,cam,v,R,np,no,uf);Schur<<<nc,32>>>(G,pt,coff,U,v,ub,nc,no,sb);Schur<<<nc,32>>>(G,pt,coff,U,v,uf,nc,no,sf);std::vector<double>hb(3ul*np),hf(hb.size()),hsb(9ul*nc),hsf(hsb.size());CK(cudaMemcpy(hb.data(),ub,hb.size()*8,cudaMemcpyDeviceToHost));CK(cudaMemcpy(hf.data(),uf,hf.size()*8,cudaMemcpyDeviceToHost));CK(cudaMemcpy(hsb.data(),sb,hsb.size()*8,cudaMemcpyDeviceToHost));CK(cudaMemcpy(hsf.data(),sf,hsf.size()*8,cudaMemcpyDeviceToHost));std::vector<double>du(hb.size()),ds(hsb.size());for(size_t i=0;i<du.size();++i)du[i]=hf[i]-hb[i];for(size_t i=0;i<ds.size();++i)ds[i]=hsf[i]-hsb[i];double nu=Norm(hb),ns=Norm(hsb);printf("CHECK seed=%d probe=%d u_abs=%.17g u_rel=%.17g s_abs=%.17g s_rel=%.17g finite=%d\n",seed,probe,Norm(du),nu?Norm(du)/nu:0,Norm(ds),ns?Norm(ds)/ns:0,std::isfinite(nu)&&std::isfinite(ns));}}
 for(int rep=0;rep<3;++rep)for(int q=0;q<2;++q){int arm=(q+rep)&1;for(int warm=0;warm<3;++warm){if(!arm){CK(cudaMemset(t,0,3ul*np*8));PointPass1<<<np,32>>>(G,dpo,dor,cam,v,np,no,t);ApplyVinv<<<(np+255)/256,256>>>(R,t,np,ub);}else Fused<<<(np+3)/4,128>>>(G,dpo,dor,cam,v,R,np,no,uf);}cudaEventRecord(a);for(int it=0;it<20;++it){if(!arm){CK(cudaMemset(t,0,3ul*np*8));PointPass1<<<np,32>>>(G,dpo,dor,cam,v,np,no,t);ApplyVinv<<<(np+255)/256,256>>>(R,t,np,ub);}else Fused<<<(np+3)/4,128>>>(G,dpo,dor,cam,v,R,np,no,uf);}cudaEventRecord(b);cudaEventSynchronize(b);float ms;cudaEventElapsedTime(&ms,a,b);printf("TIME rep=%d arm=%s products=20 chain_ms=%.9g per_product_ms=%.9g\n",rep,arm?"fused":"baseline",ms,ms/20);fflush(stdout);}
 return 0;}catch(const std::exception&e){fprintf(stderr,"%s\n",e.what());return 1;}}
