// Auto-generated by gen_gradonly.py -- Gauss-Newton specialization.
// CSE run over the 18 gradient entries + 2 residuals ONLY; the 162
// second-derivative entries are never constructed.
#pragma once

__device__ __forceinline__ void BalResidualGradOnly(
    Scalar R00,Scalar R01,Scalar R02,Scalar R10,Scalar R11,Scalar R12,
    Scalar R20,Scalar R21,Scalar R22,
    Scalar t0x,Scalar t0y,Scalar t0z,Scalar X0x,Scalar X0y,Scalar X0z,
    Scalar f_,Scalar k1_,Scalar k2_,Scalar ux,Scalar uy,
    Scalar* __restrict__ grad_res_x, Scalar* __restrict__ grad_res_y,
    Scalar* __restrict__ res_x, Scalar* __restrict__ res_y) {
  Scalar x0 = R10*X0x + R11*X0y + R12*X0z;
  Scalar x1 = R20*X0x + R21*X0y + R22*X0z;
  Scalar x2 = t0z + x1;
  Scalar x3 = pow(x2, -2);
  Scalar x4 = R00*X0x + R01*X0y + R02*X0z;
  Scalar x5 = t0x + x4;
  Scalar x6 = pow(x5, 2);
  Scalar x7 = t0y + x0;
  Scalar x8 = pow(x7, 2);
  Scalar x9 = x6 + x8;
  Scalar x10 = x3*x9;
  Scalar x11 = k1_*x10 + k2_*pow(x9, 2)/pow(x2, 4) + 1;
  Scalar x12 = x0*x11;
  Scalar x13 = 1.0/x2;
  Scalar x14 = x0*x13;
  Scalar x15 = x1*x7 + x14*x6 + x14*x8;
  Scalar x16 = 2*x10;
  Scalar x17 = k1_ + k2_*x16;
  Scalar x18 = 2*x17;
  Scalar x19 = x13*x18;
  Scalar x20 = f_*x3;
  Scalar x21 = x20*x5;
  Scalar x22 = x1*x11;
  Scalar x23 = x11*x4;
  Scalar x24 = x13*x4;
  Scalar x25 = x1*x5 + x24*x6 + x24*x8;
  Scalar x26 = x18*x3;
  Scalar x27 = x26*x5;
  Scalar x28 = f_*x13;
  Scalar x29 = -x0*x5 + x4*x7;
  Scalar x30 = -f_*x18*x5*x7/pow(x2, 3);
  Scalar x31 = x11 + x16*x17;
  Scalar x32 = R20*x13;
  Scalar x33 = x11*x5;
  Scalar x34 = -R00*x5 - R10*x7 + R20*x13*x6 + R20*x13*x8;
  Scalar x35 = R21*x13;
  Scalar x36 = -R01*x5 - R11*x7 + R21*x13*x6 + R21*x13*x8;
  Scalar x37 = R22*x13;
  Scalar x38 = -R02*x5 - R12*x7 + R22*x13*x6 + R22*x13*x8;
  Scalar x39 = x26*x7;
  Scalar x40 = x20*x7;
  Scalar x41 = x11*x7;
  grad_res_x[0] = x21*(x12 + x15*x19);
  grad_res_x[1] = -x28*(x13*x23*x5 + x22 + x25*x27);
  grad_res_x[2] = x28*(x0*x11 - x27*x29);
  grad_res_x[3] = -x28*(x11 + x26*x6);
  grad_res_x[4] = x30;
  grad_res_x[5] = x21*x31;
  grad_res_x[6] = x28*(-R00*x11 + x27*x34 + x32*x33);
  grad_res_x[7] = x28*(-R01*x11 + x27*x36 + x33*x35);
  grad_res_x[8] = x28*(-R02*x11 + x27*x38 + x33*x37);
  grad_res_y[0] = x28*(x12*x13*x7 + x15*x39 + x22);
  grad_res_y[1] = -x40*(x19*x25 + x23);
  grad_res_y[2] = -x28*(x23 + x29*x39);
  grad_res_y[3] = x30;
  grad_res_y[4] = -x28*(x11 + x26*x8);
  grad_res_y[5] = x31*x40;
  grad_res_y[6] = x28*(-R10*x11 + x32*x41 + x34*x39);
  grad_res_y[7] = x28*(-R11*x11 + x35*x41 + x36*x39);
  grad_res_y[8] = x28*(-R12*x11 + x37*x41 + x38*x39);
  *res_x = -ux - x28*x33;
  *res_y = -uy - x28*x41;
}
