#!/usr/bin/env python3
import pathlib,json,statistics,re,hashlib
R=pathlib.Path('/workspace/prism-tr-point-prep');repo=pathlib.Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
rows=[]
for p in R.glob('repeat-*/results.json'):rows+=json.loads(p.read_text())
text=['# Point preparation and fresh Caspar comparison','', 'Current results use independently audited original-double observations, the same scene target for all arms, and solver-native time to the qualified target. Caspar FP32 uses the established 0.1% tighter native stopping margin. This is an empirical guard, not a certified rounding bound. Input loading is excluded; established solver setup-scope differences remain. GPU jobs were serialized. CPU builds and audits could overlap loading.','', '## Fresh confirmation','', '| Scene | Arm | Runs/hits | Median qualifying seconds |','|---|---|---:|---:|']
if (R/'other-large/results.json').exists():rows+=json.loads((R/'other-large/results.json').read_text())
for scene in dict.fromkeys(r['scene'] for r in rows):
 for arm in ['control','factored','caspar32']:
  rr=[r for r in rows if r['scene']==scene and r['arm']==arm];hits=[r['crossing'] for r in rr if r['hit']];v=f'{statistics.median(hits):.6f}' if len(hits)==len(rr) and rr else 'miss within 20s';text.append(f'| {scene} | {arm} | {len(rr)}/{len(hits)} | {v} |')
text+=['','Control is old guarded projected TR; factored changes FP64 derivatives and computes directional Jd directly. Read protocol-amendment.json for the inherited scope-label correction. The frozen binary hashes and flags were correct. Final13682 has N=3, Final4585 N=1. These scenes do not establish universal superiority.','', '## Fixed-system experiments','', 'The fused observation-owned kernel reads each float W block once for both FP64 RHS correction and the FP64 forward-solve diagonal. It preserves the matrix and arithmetic precision; atomic arrival order can change. This differs from earlier camera-owned/full-backsolve fusion experiments.','', '```', (R/'fusion.log').read_text().strip(),'```','', 'For point factors, accumulate A = B^T B from the same stored float Jacobian in FP64, then form an upper Cholesky factor R. Accept it only with positive finite diagonals, a small reconstruction residual, and the conditioning screen below. Otherwise run the original Givens QR over the observations. Damping continues through the original QR augmentation, preserving the cached undamped factor interface.','', '`budget = 64 * eps64 * max(1, 2 * track_length)`','', '`budget * ||R||_F^2 * ||R^-1||_F^2 < 1e-8` and `maxabs(R^T R - A) <= budget * maxabs(A)`.','', 'The Frobenius product bounds the spectral condition number of the computed factor product in exact arithmetic. This is a conservative floating-point screening rule, not an interval-certified error bound. There are no scene-specific thresholds. The normal-equation approach loses QR stability near singularity, hence the mandatory fallback. No point damping policy or nonlinear acceptance rule changes.','', 'The captured system contains all 4,456,117 points / 28,987,644 observations of the initial Final13682 linearization. The extended test compares all factors, actual-RHS inverse actions, and all three inverse columns at damping 10, 0.1, 1e-4, 1e-8. It does not cover every later linearization.','', '```', (R/'cholesky-extended.log').read_text().strip(),'```']
for folder in ['fused-small','combined-small','fused-large','combined-large','combined-other']:
 p=R/folder/'summary.json'
 if not p.exists():continue
 text+=['', '## '+folder,'','Historical harness labels: double = factored control; storage = candidate. Candidate manifest gives the exact source/binary.','', '| Scene | Control seconds | Candidate seconds | Candidate change |','|---|---:|---:|---:|']
 for row in json.loads(p.read_text()):
  a=row['double']['median_crossing'];b=row['storage']['median_crossing'];text.append(f"| {row['scene']} | {a if a is not None else 'miss'} | {b if b is not None else 'miss'} | {(str(round(100*(b/a-1),2))+'%') if a and b else 'n/a'} |")
text+=['', '## Numerical edge cases', '', (R/'synthetic.log').read_text().strip()]
if (R/'combined-profile/result.json').exists():
 text+=['','## Instrumented attribution','','Point preparation fell from 3.113s in the previous factored profile to 1.288s in the new seven-outer profile (about 59% less). Krylov remains 7.220s and assembly 2.071s: those are now the leading costs. The observed 1.825s phase saving agrees with the 1.827s paired native saving. Guarded factors total 0.233s; fused RHS/diagonal totals 0.965s. These measurements attribute this trajectory, not every BA instance.','','Separate seven-outer Nsight/profile run; excluded from benchmark ratios. The kernel table and synchronized phase timings are in `combined-profile/final-13682.kernels.csv` and `.log`. Endpoint independently audited.']
if (R/'combined-large/summary.json').exists() and (R/'combined-other/summary.json').exists():
 a=json.loads((R/'combined-large/summary.json').read_text())[0];b=json.loads((R/'combined-other/summary.json').read_text())[0];cas=statistics.median(r['crossing'] for r in rows if r['scene']=='final-13682' and r['arm']=='caspar32');verdict=dict(candidate='combined',final13682_seconds=a['storage']['median_crossing'],final13682_factored_seconds=a['double']['median_crossing'],caspar32_final13682_median=cas,final4585_seconds=b['storage']['median_crossing'],largest_candidate_runs=1)
 (R/'verdict.json').write_text(json.dumps(verdict,indent=2));text[2:2]=['**Verdict:** the combined FP64 fused RHS/diagonal plus guarded-Cholesky candidate is the best tested PRISM option on the two large scenes in this study. Final13682: %.3fs versus factored %.3fs and Caspar FP32 median %.3fs; Final4585: %.3fs while Caspar FP32 misses the 20s budget. Largest-candidate comparisons are N=1; small-panel medians use N=3. Keep the candidate opt-in. These are execution optimizations, not evidence by themselves of a new optimization algorithm.'%(verdict['final13682_seconds'],verdict['final13682_factored_seconds'],cas,verdict['final4585_seconds']), '']
text+=['','## Reproduction and limits','', 'Artifacts: `/workspace/prism-tr-point-prep`. Builders, harnesses and report generator: `bench/*point_prep*.py`; candidate kernels: `gpu/point_prep_candidate.cuh`. Frozen candidate builds include the complete source, headers, compiler command and hashes. A self-contained package includes the tested binary, rebuild script, flags and results. Production `gpu/oca_cuda.cu` is unchanged in this study.','', 'Capture v1 failed because it attempted to read the unused optional Bo32 pointer. Capture v2 uses the active float buffer. The initial fused build similarly targeted the unused optional path and was not BA tested; fused-v2 fixes activation. Failed/unused artifacts are retained.','', 'No hardware-counter profiling was attempted again because the driver denied access in the preceding study. The 11 pre-existing paused jobs were not resumed. No push or production-default change was made.']
if (R/'package-smoke.json').exists():text+=['', 'The self-contained package was rebuilt successfully, and its rebuilt binary reached the Trafalgar target with an independent original-double endpoint audit (zero reported/audited cost difference in this smoke run). This additional run is excluded from the comparison medians and the 54 timed-endpoint count.']
(repo/'docs/point_preparation_results.md').write_text('\n'.join(text)+'\n')
allrows=list(rows)
for folder in ['fused-small','combined-small','fused-large','combined-large','combined-other']:
 p=R/folder/'results.json'
 if p.exists():allrows+=json.loads(p.read_text())
assert all(r['returncode']==0 and r['audit_error']<1e-7 for r in allrows)
checks=[]
for p in R.glob('**/*.log'):
 if p.parent.name not in ['fused-small','combined-small','fused-large','combined-large','combined-other'] and not p.parent.name.startswith('repeat-') and p.parent.name!='other-large':continue
 for line in p.read_text().splitlines():
  if line.startswith('CAMERA_TR o='):
   v={k:float(x) for k,x in re.findall(r'(\w+)=([^ ]+)',line)}
   if v.get('accept'):assert v['rho']>=.1 and v['prediction']>0 and v['norm']<=v['radius']*(1+1e-8);checks.append(v)
for m in R.glob('**/stop-manifest.json'):
 if 'package' in str(m):continue
 d=json.loads(m.read_text());assert sha(m.parent/'prism-tr')==d['binary_sha256'];assert sha(m.parent/'source.cu')==d['source_sha256'];assert all(sha(m.parent/'headers'/k)==v for k,v in d['headers_sha256'].items())
prod=sha(repo/'gpu/oca_cuda.cu');assert prod=='0b7aac9b70523ce08d791e1a75c6c18a672cdfb29f28c6a3ab21c0bf5e786569'
(R/'verification.json').write_text(json.dumps(dict(completed_ba_endpoints=len(allrows),target_hits=sum(r['hit'] for r in allrows),accepted_log_checks=len(checks),production_sha256=prod,recorded_native_seconds=sum(r['seconds'] for r in allrows)),indent=2));print((R/'verification.json').read_text())
