#!/usr/bin/env python3
"""Build isolated experiments from the checksum-verified frozen eta2 source."""
import argparse, hashlib, json, pathlib, shutil, subprocess
ROOT=pathlib.Path(__file__).resolve().parent
PKG=ROOT.parent/'eta2_champion'
OUT=ROOT/'build'; OUT.mkdir(exist_ok=True)
ap=argparse.ArgumentParser();ap.add_argument('--part',choices=['capture','fixed','solver','menu'],required=True)
args=ap.parse_args()
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
manifest=json.loads((PKG/'source_manifest.json').read_text())
source=PKG/'source/prism_eta2.cu'
assert sha(source)==manifest['source_sha256']
assert all(sha(PKG/'source/headers'/name)==h for name,h in manifest['headers_sha256'].items())
s=source.read_text()
headers=OUT/('headers_'+args.part);headers.mkdir(exist_ok=True)
for p in (PKG/'source/headers').iterdir():shutil.copy2(p,headers/p.name)
shutil.copy2(ROOT/'coarse.cuh',headers/'coarse.cuh')
shutil.copy2(ROOT/'gradient_audit.cuh',headers/'gradient_audit.cuh')
parts=[]
for start,end in [('__device__ __forceinline__ void MFVinv(', '// GAP-4090 F2'),('__global__ void MFVinvApply(', '// Map camera traversal'),('template <int CD, class HT>\n__global__ void MFPass2(', '__global__ void MFBackSub'),('template <int CD, typename HT>\n__global__ void MFBlockSchur(', '#include "pcg_camera.cuh"')]:
 a=s.index(start);b=s.index(end,a);parts.append(s[a:b])
(OUT/'reference.cuh').write_text('\n'.join(parts))
factor_parts=[]
for start,end in [('__device__ __forceinline__ void MFGivens(', 'template <class HT>'),('__global__ void MFPointFactorTau(', '__device__ __forceinline__ void MFVinv(')]:
 a=s.index(start);b=s.index(end,a);factor_parts.append(s[a:b])
(OUT/'point_factor.cuh').write_text('\n'.join(factor_parts))
if args.part=='capture':
 old='if(camera_tr && getenv("OCA_CG_CAPTURE") && k=='
 assert s.count(old)==1;s=s.replace(old,'if(getenv("OCA_CG_CAPTURE") && k==')
 old='      std::string dir=getenv("OCA_CG_CAPTURE");'
 s=s.replace(old,'''      if(!classical_lm || CD!=9 || compact_mode!=2 || L!=1 || !tau_split)
        throw std::runtime_error("capture requires frozen classical eta2 split-point layout");
'''+old)
 old='      prism_cg_save(dir+"/R",Rf,(size_t)npt*6*8);'
 s=s.replace(old,old+'''
      prism_cg_save(dir+"/R0",R0f,(size_t)npt*6*8);
      prism_cg_save(dir+"/Cdiag",Cdiag,(size_t)npt*3*8);
      prism_cg_save(dir+"/bc",bc,(size_t)n_cf*8);
      prism_cg_save(dir+"/bp",bp,(size_t)n_p*8);
''')
 old='(double)shifts[0],tr->radius,(double)eta);fclose(f);'
 assert s.count(old)==1
 s=s.replace(old,'''(double)shifts[0],0.0,(double)eta);fclose(f);
      std::printf("FIXED_CAPTURE outer=%d cost=%.17g tau=%.17g lambda=%.17g eta=%.17g\\n",k,(double)cost,(double)tau_eff,(double)shifts[0],(double)eta);
      std::fflush(stdout);std::exit(0);''')
 unit=OUT/'capture.cu';unit.write_text(s);binary=OUT/'capture'
elif args.part=='solver':
 # Generated by a separate, reviewable transformation; original files unchanged.
 from solver_patch import patch
 s=patch(s,headers)
 unit=OUT/'solver.cu';unit.write_text(s);binary=OUT/'prism-coarse'
else:
 unit=ROOT/(args.part+'.cu');binary=OUT/args.part
cmd=['nvcc','-O3','-DNDEBUG','-std=c++17','-arch=sm_89','-I/usr/include/eigen3','-I'+str(headers),'-I'+str(OUT),str(unit),'-o',str(binary),'-lcublas','-lcusolver']
print('Building',args.part,flush=True)
with (OUT/('build-'+args.part+'.log')).open('w') as f:
 subprocess.run(cmd,stdout=f,stderr=subprocess.STDOUT,check=True)
(OUT/(args.part+'-manifest.json')).write_text(json.dumps({'command':cmd,'frozen_manifest':manifest,'source_sha256':sha(unit),'binary_sha256':sha(binary),'coarse_sha256':sha(ROOT/'coarse.cuh'),'generated_headers':{p.name:sha(p) for p in headers.iterdir()},'reference_headers':{name:sha(OUT/name) for name in ['reference.cuh','point_factor.cuh']}},indent=2)+'\n')
print(binary,flush=True)
